// 🎯 BotTargetRandomizer.java
// @Generated by ChatGPT — Охотник за случайной целью 😎

package com.devone.bot.core.brain.logic.navigator.math.selector;

import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

import com.devone.bot.core.utils.blocks.BotBlockData;
import com.devone.bot.core.utils.blocks.BotLocation;
import com.devone.bot.core.utils.logger.BotLogger;
import com.devone.bot.core.utils.world.BotWorldHelper;

public class BotBlockSelector {

    private static final Random RANDOM = new Random();

    /**
     * Выбирает случайную точку из списка.
     *
     * @param targets список доступных точек
     * @return одна случайная точка или null, если список пуст или null
     */
    public static BotBlockData selectRandomTarget(List<BotBlockData> targets) {
        if (targets == null || targets.isEmpty()) {
            return null;
        }
        int index = RANDOM.nextInt(targets.size());
        return targets.get(index);
    }

    public static BotBlockData selectNearestTarget(List<BotBlockData> targets, BotLocation fromLocation) {

        BotLogger.debug("🗺️", true, "📍Выбираем ближайшую току ");

        if (targets == null || targets.isEmpty() || fromLocation == null) {
            return null;
        }
    
        BotBlockData nearest = null;
        double minDistance = Double.MAX_VALUE;
    
        for (BotBlockData target : targets) {
            if (fromLocation.equals(target.getLocation())) {
                BotLogger.debug("🗺️", true, "❌ Точка совпадает к текущей позицией, игнорируем.");
                continue;
            }
    
            double distance = fromLocation.distanceTo(target);
            if (distance < minDistance) {
                minDistance = distance;
                nearest = target;
            }
        }
    
        return nearest;
    }
    

    public static BotBlockData pickEmergencyRelocationTarget(
            BotLocation botPos,
            List<BotBlockData> reachableGoals,
            List<BotBlockData> reachable,
            List<BotBlockData> navigable,
            List<BotBlockData> walkable) {

        List<List<BotBlockData>> prioritySources = List.of(
                reachableGoals, reachable, navigable, walkable);

        for (List<BotBlockData> source : prioritySources) {
            if (source == null || source.isEmpty())
                continue;

            List<BotBlockData> options = source.stream()
                    .filter(b -> {
                        boolean isSame = b.equals(botPos);
                        boolean isDirectlyUnder = (b.getX() == botPos.getX() && b.getZ() == botPos.getZ()
                                && b.getY() == botPos.getY() - 1);
                        return !isSame && !isDirectlyUnder && b.distanceTo(botPos) > 1;
                    })
                    .collect(Collectors.toList());

            if (!options.isEmpty()) {
                Collections.shuffle(options);
                BotBlockData selected = options.get(0);

                BotBlockData elevated = new BotBlockData();
                elevated.setX(selected.getX());
                elevated.setY(selected.getY() + 1);
                elevated.setZ(selected.getZ());
                elevated.setType("AIR");
                return elevated;
            }
        }

        // ⛔ Fallback на спавн
        BotLogger.debug("⚠️", true, "EmergencyTeleport: fallback to world spawn!");

        BotLocation spawn = BotWorldHelper.getWorldSpawnLocation();

        BotBlockData fallback = new BotBlockData();
        fallback.setX(spawn.getX());
        fallback.setY(spawn.getY());
        fallback.setZ(spawn.getZ());
        fallback.setType("AIR");
        return fallback;
    }

}
