name: AIBotPlugin
main: com.devone.bot.AIBotPlugin
version: 1.3
api-version: 1.20
author: DevOne
description: A SpigotMC plugin that allows managing AI bots with Citizens NPCs, random skins, and protected zones.

# Ensure Citizens is loaded before this plugin to avoid issues
depend:
  - Citizens 

softdepend:
  - BlueMap

# Ensures plugin loads at the correct time
load: POSTWORLD

commands:

  bot-reload-plugin:
    description: Reloads the entire AI Bot Plugin, including configuration, commands, and logging.
    usage: /bot-reload-plugin
    permission: aibotplugin.admin.reload

  bot-select:
    description: Selects a bot to receive bot commands.
    usage: /bot-select <bot_name>
    permission: aibotplugin.bot.select

  bot-unselect:
    description: unselects the currently selected bot.
    usage: /bot-unselect
    permission: aibotplugin.bot.unselect

  bot-add:
    description: Spawns a bot with a random skin and unique name.
    usage: /bot-add
    permission: aibotplugin.bot.add

  bot-list:
    description: Lists all active bots.
    usage: /bot-list
    permission: aibotplugin.bot.list

  bot-remove:
    description: Removes a bot by name.
    usage: /bot-remove <bot_name>
    permission: aibotplugin.bot.remove

  bot-remove-all:
    description: Removes all spawned bots.
    usage: /bot-remove-all
    permission: aibotplugin.bot.removeall

  bot-tp:
    description: Makes the selected bot teleport to coordinates.
    usage: /bot-tp <bot_name> <x> <y> <z>
    permission: aibotplugin.bot.tp

  bot-tp-here:
    description: Makes the selected bot teleport to the player.
    usage: /bot-tp-here
    permission: aibotplugin.bot.tp.here

  bot-move:
    description: Moves the bot to the specified coordinates.
    usage: /bot-move <bot_name> <x> <y> <z>
    permission: aibotplugin.bot.move

  bot-move-here:
    description: Makes the selected bot approach the player.
    usage: /bot-move-here
    permission: aibotplugin.bot.move.here

  bot-calibrate:
    description: Stops the selected bot from moving.
    usage: /bot-calibrate
    permission: aibotplugin.bot.stop

  bot-chase:
    description: Makes the bot chase the player.
    usage: /bot-chase
    permission: aibotplugin.bot.chase

  bot-protect:
    description: The bot will protect the player.
    usage: /bot-protect
    permission: aibotplugin.bot.protect

  bot-drop-all:
    description: Drops all items in inventory
    usage: /bot-drop-all  <bot_name>
    permission: aibotplugin.bot.drop.all 

  bot-reload:
    description: Reloads bot commands without restarting the server.
    usage: /bot-reload
    permission: aibotplugin.bot.reload

  zone-add:
    description: Adds a protected zone at your location.
    usage: /zone-add <radius> <zone_name>
    permission: aibotplugin.zone.add

  zone-remove:
    description: Removes a protected zone.
    usage: /zone-remove <zone_name>
    permission: aibotplugin.zone.remove

  zone-list:
    description: Lists all protected zones.
    usage: /zone-list
    permission: aibotplugin.zone.list

bot-dump:
    description: Dump memery blocks to the file
    usage: /bot-dump
    permission: aibotplugin.bot.dump