name: AIBotPlugin
main: com.devone.aibot.AIBotPlugin
version: 1.2
api-version: 1.20
author: DevOne
description: A PaperMC plugin that allows managing AI bots with Citizens NPCs, random skins, and protected zones.

# Ensure Citizens is loaded before this plugin to avoid issues
depend:
  - Citizens 

softdepend:
  - BlueMap

# Ensures plugin loads at the correct time
load: POSTWORLD

commands:

  bot-reload-plugin:
    description: Reloads the entire AI Bot Plugin, including configuration, commands, and logging.
    usage: /bot-reload-plugin
    permission: aibotplugin.admin.reload

  bot-select:
    description: Selects a bot to receive bot commands.
    usage: /bot-select <bot_name>
    permission: aibotplugin.bot.select

  bot-unselect:
    description: unselects the currently selected bot.
    usage: /bot-unselect
    permission: aibotplugin.bot.unselect

  bot-add:
    description: Spawns a bot with a random skin and unique name.
    usage: /bot-add
    permission: aibotplugin.bot.add

  bot-list:
    description: Lists all active bots.
    usage: /bot-list
    permission: aibotplugin.bot.list

  bot-remove:
    description: Removes a bot by name.
    usage: /bot-remove <bot_name>
    permission: aibotplugin.bot.remove

  bot-remove-all:
    description: Removes all spawned bots.
    usage: /bot-remove-all
    permission: aibotplugin.bot.removeall

  bot-here:
    description: Makes the selected bot approach the player.
    usage: /bot-here
    permission: aibotplugin.bot.here

  bot-here-tp:
    description: Makes the selected bot teleport to the player.
    usage: /bot-here-tp
    permission: aibotplugin.bot.here.tp

  bot-move:
    description: Moves the bot to the specified coordinates.
    usage: /bot-move <x> <y> <z>
    permission: aibotplugin.bot.move

  bot-stop:
    description: Stops the selected bot from moving.
    usage: /bot-stop
    permission: aibotplugin.bot.stop

  bot-follow:
    description: Makes the bot follow the player.
    usage: /bot-follow
    permission: aibotplugin.bot.follow

  bot-protect:
    description: The bot will protect the player from nearby mobs.
    usage: /bot-protect
    permission: aibotplugin.bot.protect

  bot-cancel:
    description: Clears the bot’s current task stack.
    usage: /bot-cancel
    permission: aibotplugin.bot.cancel

  bot-reload:
    description: Reloads bot commands without restarting the server.
    usage: /bot-reload
    permission: aibotplugin.bot.reload

  zone-add:
    description: Adds a protected zone at your location.
    usage: /zone-add <radius> <zone_name>
    permission: aibotplugin.zone.add

  zone-remove:
    description: Removes a protected zone.
    usage: /zone-remove <zone_name>
    permission: aibotplugin.zone.remove

  zone-list:
    description: Lists all protected zones.
    usage: /zone-list
    permission: aibotplugin.zone.list
