name: default

offsetOuter:
  x: 0
  y: 1
  z: 0

offsetInner:
  x: 0
  y: 0
  z: 0

outerRadius: 1
innerRadius: 1

inverted: true

filters:
  - "x == cx"
  - "z == cz"
  - "y <= cy && y >= cy - 3"  # Три блока вниз от центра: cy, cy-1, cy-2

sort:
  - "y"