name: around_observer

offsetOuter:
  x: 0
  y: 0
  z: 0

offsetInner:
  x: 0
  y: 0
  z: 0

outerRadius: 2
innerRadius: 1

inverted: false

filters:
  - "math.abs(x - cx) <= r"
  - "math.abs(z - cz) <= r"
  - "math.abs(x - cx) > 0 || math.abs(z - cz) > 0"
sort:
  - "y"