name: around_observer

offsetOuter:
  x: 0
  y: 0
  z: 0

offsetInner:
  x: 0
  y: 0
  z: 0

outerRadius: 1
innerRadius: 1

inverted: false

#cube with cental column
filters:
  - "x >= cx - r && x <= cx + r"
  - "y >= cy - r && y <= cy + r"
  - "z >= cz - r && z <= cz + r"
  - "!(x == cx && z == cz)"
sort:
  - "y"