// 🎯 BotTargetRandomizer.java
// @Generated by ChatGPT — Охотник за случайной целью 😎

package com.devone.bot.core.logic.navigation.selectors;

import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

import com.devone.bot.utils.blocks.BotBlockData;
import com.devone.bot.utils.blocks.BotLocation;
import com.devone.bot.utils.logger.BotLogger;
import com.devone.bot.utils.world.BotWorldHelper;

public class BotGeoSelector {

    private static final Random RANDOM = new Random();

    /**
     * Выбирает случайную точку из списка.
     *
     * @param targets список доступных точек
     * @return одна случайная точка или null, если список пуст или null
     */
    public static BotBlockData pickRandomTarget(List<BotBlockData> targets) {
        if (targets == null || targets.isEmpty()) {
            return null;
        }
        int index = RANDOM.nextInt(targets.size());
        return targets.get(index);
    }

    public static BotBlockData pickEmergencyTeleportTarget(
            BotLocation botPos,
            List<BotBlockData> reachableGoals,
            List<BotBlockData> reachable,
            List<BotBlockData> navigable,
            List<BotBlockData> walkable) {

        List<List<BotBlockData>> prioritySources = List.of(
                reachableGoals, reachable, navigable, walkable);

        for (List<BotBlockData> source : prioritySources) {
            if (source == null || source.isEmpty())
                continue;

            List<BotBlockData> options = source.stream()
                    .filter(b -> {
                        boolean isSame = b.equals(botPos);
                        boolean isDirectlyUnder = (b.getX() == botPos.getX() && b.getZ() == botPos.getZ()
                                && b.getY() == botPos.getY() - 1);
                        return !isSame && !isDirectlyUnder && b.distanceTo(botPos) > 1;
                    })
                    .collect(Collectors.toList());

            if (!options.isEmpty()) {
                Collections.shuffle(options);
                BotBlockData selected = options.get(0);

                BotBlockData elevated = new BotBlockData();
                elevated.setX(selected.getX());
                elevated.setY(selected.getY() + 1);
                elevated.setZ(selected.getZ());
                elevated.setType("AIR");
                return elevated;
            }
        }

        // ⛔ Fallback на спавн
        BotLogger.info("⚠️ ", true, "EmergencyTeleport: fallback to world spawn!");

        BotLocation spawn = BotWorldHelper.getWorldSpawnLocation();

        BotBlockData fallback = new BotBlockData();
        fallback.setX(spawn.getX());
        fallback.setY(spawn.getY());
        fallback.setZ(spawn.getZ());
        fallback.setType("AIR");
        return fallback;
    }

}
